export interface TimedEvent { readonly locationId: string; readonly arrival?: string; readonly departure?: string; readonly pass?: string; readonly boundaryTime?: string }
export interface DomainTrip { readonly tripId: string; readonly direction: "up" | "down"; readonly circulationId: string; readonly vehicleId: string; readonly classification: "revenue" | "non-revenue" | "mixed"; readonly events: readonly TimedEvent[]; readonly serviceSegments?: readonly { readonly classification: string; readonly departure: string; readonly arrival: string }[] }
export interface DomainConnection { readonly fromTripId: string; readonly toTripId: string; readonly locationId: string; readonly fromTime: string; readonly toTime: string; readonly connectionType: string }
export interface DomainCirculation { readonly circulationId: string; readonly vehicleId: string; readonly tripIds: readonly string[]; readonly connections: readonly DomainConnection[] }
export interface DomainTimetable { readonly trips: readonly DomainTrip[]; readonly circulations: readonly DomainCirculation[]; readonly conventions?: { readonly serviceDayRollover?: string } }

export function seconds(value: string): number { const match = /^(\d{2}):(\d{2}):(\d{2})$/.exec(value); if (!match) throw new Error(`Invalid time ${value}`); return Number(match[1]) * 3600 + Number(match[2]) * 60 + Number(match[3]); }
export function serviceSeconds(value: string, timetable?: DomainTimetable): number { const valueSeconds = seconds(value); const rollover = timetable?.conventions?.serviceDayRollover; return rollover !== undefined && valueSeconds < seconds(rollover) ? valueSeconds + 86_400 : valueSeconds; }
export function serviceDaySeconds(now: number, timetable: DomainTimetable): number { const rollover = timetable.conventions?.serviceDayRollover; return rollover !== undefined && now < seconds(rollover) ? now + 86_400 : now; }
export function eventTimes(event: TimedEvent, timetable?: DomainTimetable): readonly { kind: "arrival" | "departure" | "pass" | "boundary"; value: string; seconds: number }[] { const values: { kind: "arrival" | "departure" | "pass" | "boundary"; value: string; seconds: number }[] = []; if (event.arrival) values.push({ kind: "arrival", value: event.arrival, seconds: serviceSeconds(event.arrival, timetable) }); if (event.departure) values.push({ kind: "departure", value: event.departure, seconds: serviceSeconds(event.departure, timetable) }); if (event.pass) values.push({ kind: "pass", value: event.pass, seconds: serviceSeconds(event.pass, timetable) }); if (event.boundaryTime) values.push({ kind: "boundary", value: event.boundaryTime, seconds: serviceSeconds(event.boundaryTime, timetable) }); return values; }
export function tripBounds(trip: DomainTrip, timetable?: DomainTimetable): readonly [number, number] { const values = trip.events.flatMap((event) => eventTimes(event, timetable)).map((item) => item.seconds); return [Math.min(...values), Math.max(...values)]; }
export function tripDestinationId(trip: DomainTrip, timetable?: DomainTimetable): string { const destination = trip.events.flatMap((event) => eventTimes(event, timetable).map((time) => ({ locationId: event.locationId, seconds: time.seconds }))).sort((a, b) => b.seconds - a.seconds)[0]; if (!destination) throw new Error(`Trip ${trip.tripId} has no timed events`); return destination.locationId; }
export function passengerServiceAt(trip: DomainTrip, now: number, timetable?: DomainTimetable): boolean { if (trip.classification === "revenue") return true; if (trip.classification === "non-revenue") return false; return trip.serviceSegments?.some((segment) => segment.classification === "revenue" && now >= serviceSeconds(segment.departure, timetable) && now <= serviceSeconds(segment.arrival, timetable)) ?? false; }
export function serviceDaySecondsAt(now: Date): number { const parts = new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Shanghai", hour: "2-digit", minute: "2-digit", second: "2-digit", hourCycle: "h23" }).formatToParts(now); const get = (type: string): number => Number(parts.find((part) => part.type === type)?.value ?? 0); return get("hour") * 3600 + get("minute") * 60 + get("second"); }
export function serviceCalendarAt(now: Date): "weekday" | "weekend" { const serviceDate = new Date(now.getTime() - 3 * 3600 * 1000); const weekday = new Intl.DateTimeFormat("en-US", { timeZone: "Asia/Shanghai", weekday: "short" }).format(serviceDate); return weekday === "Sat" || weekday === "Sun" ? "weekend" : "weekday"; }
